### PR TITLE
Tutorials Updated for RS5

### PR DESCRIPTION
**Pull request by kyaoNV**

### CODE REVIEW

**Comment by nbentyNV** [comment]
Is the following really required in tutorial 3?
```
We also create them with the D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS (not mentioned in the spec but probably required). 
```
Not sure if that's true anymore. Can you check and remove it from the tutorials if it's not required? We should fix Falcor as well - please open an issue

**Comment by nbentyNV** [comment]
Tutorial 4 - 
> Note that the shader compiler expects the intersection attributes to be a struct – it can’t be an integral type. 

We don't need that anymore, right? Is the builtinIntersection struct is an HLSL builtin? If it is, clarify it

**Comment by nbentyNV** [comment]
Tutorial 5 - 
The SBT has some alignment requirements for each entry, you should mention it. I also don't see any mention to the size of the shader-identifier in the doc

**Comment by nbentyNV** [comment]
Tutorial 4:
> Any Hit Shader will be invoked for every intersection found in the traversal

Not true. I don't remember when exactly it will be invoked, please consult Chris on how to re-phrase this paragraph

**Comment by nbentyNV** [comment]
You removed this from tutorial 8:
> The last thing we need to change is the call to BuildRaytracingAccelerationStructure(). We need to set the NumDescs field of D3D12_BUILD_RAYTRACING_ACCELERATION_STRUCTURE_DESC to 3.

You need to mention somewhere that we changed `inputs.NumDescs = 3;`

**Comment by kyaoNV** [comment]
Tutorial 8: The `inputs.NumDescs = 3` was the first thing mentioned, though it's probably worth adding that it will be picked up automatically through `D3D12_BUILD_RAYTRACING_ACCELERATION_STRUCTURE_DESC.Inputs`

**Comment by nbentyNV** [comment]
Type in 12.docx, plane hit-prog section:
> We to make the following changes to

**Pull request merged**
